#!/bin/bash

set -eu

instance="${1:-}"
app="${2:-}"

workspace="$(realpath "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../..")"

if [ "$instance" == "" ]
then
	echo -e " \033[1m- Please specify an instance id\033[0m"
	exit 1
fi

if [ "$app" == "" ]
then
	echo -e " \033[1m- Please specify an app id\033[0m"
	exit 1
fi

if [ ! -d "$workspace/instances/master/apps-extra/$app" ]
then
	echo "Cloning $app."
	git clone "git@github.com:nextcloud/$app.git" "$workspace/instances/master/apps-extra/$app"
	git -C "$workspace/instances/master/apps-extra/$app" fetch --force --tags --prune --prune-tags --recurse-submodules --quiet
fi

if [ ! -d "$workspace/instances/$instance/apps-extra/$app" ]
then
	mainBranch="$(git -C "$workspace/instances/master/apps-extra/$app" rev-parse --verify --quiet --abbrev-ref origin/HEAD --)"
	mainBranch="${mainBranch#origin/}"

	git -C "$workspace/instances/master/apps-extra/$app" worktree add --quiet --force "$workspace/instances/$instance/apps-extra/$app" "$instance" ||
	git -C "$workspace/instances/master/apps-extra/$app" worktree add --quiet --force "$workspace/instances/$instance/apps-extra/$app" "$mainBranch" ||
	git -C "$workspace/instances/master/apps-extra/$app" worktree add --quiet --force "$workspace/instances/$instance/apps-extra/$app" "master"
fi

git -C "$workspace/instances/$instance/apps-extra/$app" fetch --force --tags --prune --prune-tags --recurse-submodules --quiet || echo "Failed to fetch $app"
git -C "$workspace/instances/$instance/apps-extra/$app" pull --quiet || echo "Failed to pull $app"
composer --quiet --working-dir "$workspace/instances/$instance/apps-extra/$app" install

cd "$workspace/instances/$instance"
php ./occ app:enable "$app"
