#!/bin/bash

set -e

token="$ZAMMAD_TOKEN" # get it from Zammad, with permission: ticket.agent
user="$ZAMMAD_USER" # url encode, e.g. escape whitespace with %20, encode umlaut
userID="$ZAMMAD_USER_ID"

if [ $# -eq 0 ]
then
    monday=$(date -d "last monday" +%F)
else
    # Format: 2022-08-29
    monday=$1
fi

sunday=$(date -d "$monday + 6 days" +%F)

echo "Range: $monday - $sunday"
echo
response=$(
    curl 2>/dev/null \
        --request GET \
        --url "https://support.nextcloud.com/api/v1/tickets/search?query=article.from%3A%22$user%22%20and%20article.created_at%3A%5B$monday%20TO%20$sunday%5D" \
        --header "authorization: Token token=$token"
)
tickets=$(echo "$response" | jq '.tickets')

for ticketId in $(echo "$tickets" | jq '.[]')
do
    articles=$(
        curl \
            --silent \
            --request GET \
            --url "https://support.nextcloud.com/api/v1/ticket_articles/by_ticket/$ticketId" \
            --header "authorization: Token token=$token"
        )

    ownerId=$(echo "$response" | jq --raw-output ".assets.Ticket[\"$ticketId\"].owner_id")
    owner=$(echo "$response" | jq --raw-output ".assets.User[\"$ownerId\"].firstname")

    if [ "$( echo "$articles" | jq ".[] | select((.created_by_id == $userID) and (.updated_at >= \"$monday\"))" | wc -l )" -gt 0 ]
    then
        if [ "$ownerId" == "$userID" ]
        then
            echo " - Follow-up on ticket [#$ticketId](https://support.nextcloud.com/#ticket/zoom/$ticketId)"
        else
            echo " - Helped $owner with ticket [#$ticketId](https://support.nextcloud.com/#ticket/zoom/$ticketId)"
        fi
    fi
done
