#!/bin/bash

set -e

token="$ZAMMAD_TOKEN" # get it from Zammad, with permission: ticket.agent
user="$ZAMMAD_USER" # url encode, e.g. escape whitespace with %20, encode umlaut
userID="$ZAMMAD_USER_ID"

if [ $# -eq 0 ]
then
    monday=$(date -d "last monday" +%F)
else
    # Format: 2022-08-29
    monday=$1
fi

sunday=$(date -d "$monday + 6 days" +%F)

echo "Range: $monday - $sunday"

articles=$(
    curl 2>/dev/null \
        --request GET \
        --url "https://support.nextcloud.com/api/v1/tickets/search?query=article.from%3A%22$user%22%20and%20article.created_at%3A%5B$monday%20TO%20$sunday%5D" \
        --header "authorization: Token token=$token"
)

# for ticketId in $(echo "$articles" | jq -cr '.[]')
for ticketBase64 in $(echo "${articles}" | jq -r '.[] | @base64')
do
    ticket=$(echo $ticketBase64 | base64 --decode)
    ticketId=$(echo $ticket | jq -r '.id')

    articles=$(
        curl \
            --silent \
            --request GET \
            --url "https://support.nextcloud.com/api/v1/ticket_articles/by_ticket/$ticketId" \
            --header "authorization: Token token=$token"
        )

    ownerId=$(echo $ticket | jq -r '.owner_id')

    if [ "$( echo "$articles" | jq ".[] | select((.created_by_id == $userID) and (.updated_at >= \"$monday\"))" | wc -l )" -gt 0 ]
    then
        if [ "$ownerId" == "$userID" ]
        then
            echo " - Follow-up on ticket [#$ticketId](https://support.nextcloud.com/#ticket/zoom/$ticketId)"
        else
            owner=$(
                curl \
                    --silent \
                    --request GET \
                    --url "https://support.nextcloud.com/api/v1/users/$ownerId" \
                    --header "authorization: Token token=$token"
                )

            ownerFirstName=$(echo $owner | jq -r '.firstname')

            echo " - Helped $ownerFirstName with ticket [#$ticketId](https://support.nextcloud.com/#ticket/zoom/$ticketId)"
        fi
    fi
done
