#!/bin/bash

set -eu

instance="${1:-}"
app="${2:-}"

workspace="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/.."

if [ "$instance" == "" ]
then
	mapfile -t instances < <(find "$workspace" -maxdepth 3 -name config.php)

	if [ "${#instances[@]}" == "0" ]
	then
		echo "No instance found, exiting."
		exit 0
	fi

	echo -e " \033[1m- Found ${#instances[@]} instances, which one do you want to link into ?\033[0m "

	for i in "${!instances[@]}"
	do
		instance_name=$(basename "$(dirname "$(dirname "${instances[$i]}")")")
		echo "    - $instance_name"
	done

	read -rp "> " instance
fi

if [ "$app" == "" ]
then
	echo -e " \033[1m- Which app do you want to link ? (Ex: backup, ...)\033[0m"

	mapfile -t apps < <(ls "$workspace/apps")

	if [ "${#apps[@]}" != "0" ]
	then
		for i in "${!apps[@]}"
		do
			echo "    - ${apps[$i]}"
		done
	fi

	read -rp "> " app
fi

cd "$workspace/$instance"
rm -rf "$workspace/$instance/apps/$app"
php ./occ app:enable "$app"